gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

- jekyll-feed

url: 
baseurl: ""
excerpt_separator: <!--endpreview-->

disqus: officetoadventure.disqus.com

collections:
   authors:

# permalink: /blog/:year/:month/:day/:title/
